import Groq from "groq-sdk";

function getGroqClient(): Groq | null {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey || apiKey === "your-groq-api-key-here") return null;
  return new Groq({ apiKey });
}

const SYSTEM_PROMPT = `You are a clinical health protocol assistant. You analyze blood work results and generate personalized daily health protocols.

When given blood work data, you must:
1. Identify all biomarkers and their values
2. Flag any values outside normal ranges (high or low)
3. Generate a structured daily protocol that includes:
   - Morning routine recommendations
   - Dietary suggestions (specific foods, supplements)
   - Exercise recommendations
   - Hydration guidelines
   - Sleep recommendations
   - Any lifestyle modifications
   - Supplements with dosages (if applicable)
4. Provide a brief summary of the overall health picture

IMPORTANT:
- Always note that this is AI-generated and must be reviewed by a physician before following.
- Use markdown formatting for readability.
- Be specific with dosages, timing, and frequencies.
- Flag any critical values that need immediate medical attention.`;

export async function analyzeBloodWork(extractedText: string): Promise<{
  protocol: string;
  summary: string;
}> {
  const groq = getGroqClient();

  if (!groq) {
    // Generate a structured mock protocol when no API key is configured
    return generateMockProtocol(extractedText);
  }

  const completion = await groq.chat.completions.create({
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      {
        role: "user",
        content: `Please analyze the following blood work results and generate a comprehensive daily health protocol:\n\n${extractedText}`,
      },
    ],
    model: "llama-3.3-70b-versatile",
    temperature: 0.3,
    max_tokens: 4000,
  });

  const content = completion.choices[0]?.message?.content || "";

  const summaryMatch = content.match(/## (?:Summary|Overview)[^\n]*\n([\s\S]*?)(?=\n##|$)/i);
  const summary = summaryMatch
    ? summaryMatch[1].trim().slice(0, 300)
    : content.slice(0, 300);

  return {
    protocol: content,
    summary,
  };
}

function generateMockProtocol(extractedText: string): {
  protocol: string;
  summary: string;
} {
  const snippet = extractedText.slice(0, 200).replace(/\n/g, " ");
  const protocol = `# Blood Work Analysis Report

> **Note:** This protocol was generated automatically. A physician must review and approve it before you follow any recommendations.

## Summary

Based on the uploaded blood work panel, an initial analysis has been performed. The extracted lab values are shown below.

## Extracted Lab Data

\`\`\`
${extractedText.slice(0, 1000)}
\`\`\`

## Daily Protocol

### Morning Routine
- Wake up at a consistent time each day
- Drink 500ml of water upon waking
- 10 minutes of light stretching or walking

### Dietary Recommendations
- Eat a balanced diet rich in whole grains, lean proteins, fruits, and vegetables
- Limit processed foods, added sugars, and excess sodium
- Include foods high in omega-3 fatty acids (salmon, walnuts, flaxseed)
- Consider iron-rich foods if hemoglobin is below range

### Supplements (pending physician review)
- Vitamin D3: 2000 IU daily (if levels are low)
- Omega-3 Fish Oil: 1000mg daily
- Magnesium Glycinate: 200mg before bed

### Exercise
- 150 minutes of moderate aerobic activity per week
- 2 sessions of resistance training per week
- Daily 10-minute walks after meals to support glucose metabolism

### Hydration
- Aim for 2-3 liters of water daily
- Reduce caffeine to 1-2 cups before noon
- Limit alcohol consumption

### Sleep
- Target 7-9 hours of quality sleep
- Maintain a consistent sleep/wake schedule
- Avoid screens 1 hour before bed

## Important Notes
- This is an AI-generated protocol and **must be reviewed by a physician** before implementation
- Individual results may vary; adjustments will be made based on doctor review
- Follow up with blood work in 3-6 months to track progress

---
*Generated by BloodWork Pro AI Analysis Engine*`;

  return {
    protocol,
    summary: `Initial analysis of blood work panel completed. Key data extracted: ${snippet}... Full protocol includes dietary, exercise, supplement, and lifestyle recommendations pending physician review.`,
  };
}
