import Link from "next/link";
import Navbar from "@/components/Navbar";
import { Activity, Upload, Brain, UserCheck, Shield, Clock } from "lucide-react";

export default function Home() {
  return (
    <>
      <Navbar />
      <main>
        {/* Hero Section */}
        <section className="relative overflow-hidden px-4 py-24 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-4xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-blue-50 px-4 py-2 text-sm font-medium text-[var(--primary)] dark:bg-blue-950">
              <Activity className="h-4 w-4" />
              AI-Powered Health Protocols
            </div>
            <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
              Your Blood Work,{" "}
              <span className="text-[var(--primary)]">Understood</span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-[var(--muted)]">
              Upload your blood work panel and receive a personalized daily health
              protocol generated by AI and verified by real doctors.
            </p>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link
                href="/signup"
                className="rounded-xl bg-[var(--primary)] px-8 py-3 text-lg font-semibold text-white shadow-lg hover:bg-[var(--primary-hover)] transition"
              >
                Get Started Free
              </Link>
              <Link
                href="/login"
                className="rounded-xl border border-[var(--border)] px-8 py-3 text-lg font-semibold hover:bg-[var(--secondary)] transition"
              >
                Log In
              </Link>
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="border-t border-[var(--border)] bg-[var(--secondary)] px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-6xl">
            <h2 className="text-center text-3xl font-bold">How It Works</h2>
            <div className="mt-12 grid gap-8 md:grid-cols-3">
              {[
                {
                  icon: Upload,
                  title: "1. Upload",
                  desc: "Upload your blood work panel as a PDF or image. We support all standard lab formats.",
                },
                {
                  icon: Brain,
                  title: "2. AI Analysis",
                  desc: "Our AI analyzes your results and generates a personalized daily health protocol.",
                },
                {
                  icon: UserCheck,
                  title: "3. Doctor Review",
                  desc: "A licensed physician reviews and approves your protocol before you see it.",
                },
              ].map(({ icon: Icon, title, desc }) => (
                <div
                  key={title}
                  className="rounded-xl border border-[var(--border)] bg-[var(--background)] p-8 text-center shadow-sm"
                >
                  <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-blue-50 text-[var(--primary)] dark:bg-blue-950">
                    <Icon className="h-7 w-7" />
                  </div>
                  <h3 className="text-xl font-semibold">{title}</h3>
                  <p className="mt-3 text-[var(--muted)]">{desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-6xl">
            <h2 className="text-center text-3xl font-bold">Why BloodWork Pro?</h2>
            <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {[
                {
                  icon: Shield,
                  title: "Doctor Verified",
                  desc: "Every protocol is reviewed by a licensed physician.",
                },
                {
                  icon: Brain,
                  title: "AI-Powered",
                  desc: "Advanced LLM analysis for comprehensive protocols.",
                },
                {
                  icon: Clock,
                  title: "Fast Turnaround",
                  desc: "Get your protocol within hours, not weeks.",
                },
                {
                  icon: Upload,
                  title: "Easy Upload",
                  desc: "PDF or image — just drag and drop your lab results.",
                },
                {
                  icon: Activity,
                  title: "Detailed Protocols",
                  desc: "Diet, exercise, supplements, and lifestyle recommendations.",
                },
                {
                  icon: UserCheck,
                  title: "Personalized",
                  desc: "Tailored to your unique blood work results.",
                },
              ].map(({ icon: Icon, title, desc }) => (
                <div
                  key={title}
                  className="flex items-start gap-4 rounded-xl border border-[var(--border)] p-6"
                >
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-[var(--primary)] dark:bg-blue-950">
                    <Icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold">{title}</h3>
                    <p className="mt-1 text-sm text-[var(--muted)]">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-[var(--border)] px-4 py-8 text-center text-sm text-[var(--muted)]">
          <p>BloodWork Pro &mdash; AI-powered health protocols verified by doctors.</p>
          <p className="mt-1">This is a demo application. Always consult your healthcare provider.</p>
        </footer>
      </main>
    </>
  );
}
